server:
  port: 8083

spring:
  datasource:
    url: jdbc:h2:mem:shop_db
  h2:
    console:
      enabled: true
      path: /h2-console
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create-drop # Recreate tables and data on each restart
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    defer-datasource-initialization: true # Ensure tables are created before data.sql runs
  sql:
    init:
      mode: always # Always run initialization scripts
      data-locations: classpath:data.sql
      continue-on-error: false

services:
  product:
    base-url: http://localhost:8082/product