server:
  port: 8087
spring:
  cloud:
    function:
      definition: receivedOrderCreatedEventForProduct;receivedOrderCreatedEventForBrand
    stream:
      bindings:
        # consumer
        receivedOrderCreatedEventForProduct-in-0:
          destination: order-created
        receivedOrderCreatedEventForBrand-in-0:
          destination: order-created
      kafka:
        binder:
          brokers: localhost:9092
        streams:
          binder:
            configuration:
              commit.interval.ms: 500
              state.dir: C:/tmp/kafka-state

          #              application.id: analytic-service
              # Default SerDes
#              default.key.serde: org.apache.kafka.common.serialization.Serdes$StringSerde
#              default.value.serde: org.springframework.kafka.support.serializer.JsonSerde
              # JsonSerde
#              spring.json.value.default.type: com.backend.shared.domain.order_product.OrderCreatedEvent
#              spring.json.trusted.packages: "*"



windowstore:
  product_name: product-windowstore
  brand_name: brand-windowstore
  size.ms: 30000