server:
  port: 8084
spring:
  datasource:
    url: jdbc:mysql://localhost:3319/order_db
    username: root
    password: root1234
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update # None change
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl

services:
  cart:
    base-url: http://localhost:8085/cart
  product:
    base-url: http://localhost:8082/product
  auth:
    base-url: http://localhost:8081/auth