server:
  port: 8082
spring:
  datasource:
    url: jdbc:mysql://localhost:3318/product_db
    username: root
    password: root1234
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update # None change
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
  cloud:
    stream:
      bindings:
        # consumer
        receivedOrderCreatedEvent-in-0:
          destination: order-created
        receivedOrderCancelledEventRestock-in-0:
          destination: order-cancelled-restock
      kafka:
        binder:
          brokers: localhost:9092
    function:
      definition: receivedOrderCreatedEvent;receivedOrderCancelledEventRestock