server:
  port: 8082
spring:
  datasource:
    url: jdbc:mysql://localhost:3318/product_db
    username: root
    password: root1234
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update # None change
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
  cloud:
    stream:
      bindings:
        receivedOrderCreatingEvent-in-0:
          destination: order-created
        receivedOrderCancellingEvent-in-0:
          destination: order-cancelled
      kafka:
        binder:
          brokers: localhost:9092
    function:
      definition: receivedOrderCreatingEvent;receivedOrderCancellingEvent