server:
  port: 8086

langchain4j:
  google-ai-gemini:
    chat-model:
      api-key: AIzaSyBB184eqOeredUZ425_SED4VllsFOb0aFw
      model-name: gemini-2.0-flash
      strict-tools: true
      temperature: 0.0
      timeout: PT60S
      log-requests: false
      log-responses: false
#      max-retries: 3
#      retry-delay: PT5S

logging:
  level:
    dev:
      langchain4j: DEBUG

services:
  cart:
    base-url: http://localhost:8085/cart
  product:
    base-url: http://localhost:8082/product
  auth:
    base-url: http://localhost:8081/auth
  order:
    base-url: http://localhost:8084/order