server:
  port: 8086

langchain4j:
  google-ai-gemini:
    chat-model:
      api-key: AIzaSyCUc5hh0ul-v9mZiiq1gxrdsfwQ6HlIJsk
      model-name: gemini-2.0-flash-lite
      strict-tools: true
      temperature: 0.0
      timeout: PT60S
      log-requests: false
      log-responses: false

logging:
  level:
    dev:
      langchain4j: DEBUG
