server:
  port: 8085
spring:
  datasource:
    url: jdbc:mysql://localhost:3320/cart_db
    username: root
    password: root1234
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update # None change
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
  cloud:
    stream:
      bindings:
        # cosumer
        receivedOrderCreatingEvent-in-0:
          destination: order-created
      kafka:
        binder:
          brokers: localhost:9092
    function:
      definition: receivedOrderCreatingEvent

services:
  product:
    base-url: http://localhost:8082/product
  shop:
    base-url: http://localhost:8083/shop